config/routes.rb
TestMongoid::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications
  
   post "/delete_globall" => "connections#set_to_nil"

   get "/create_connection" => "connections#new"

   get "/find_connection" => "connections#find"

    get "/choose" => "connections#choose"

  get "/create_resume_from_social_facebook" => "connections#create_resume_from_social_facebook"

  get "/create_resume_from_social_vk" => "connections#create_resume_from_social_vk"

  get "omniauth_callbacks/facebook"

  mount TinymceFm::Engine => "/tinymce_fm"

  resource :images

  resources :months do
    collection do
      post 'update_calendar'
    end
  end

  resources :areas do
    collection do
      post 'add_to_user'
      get 'list'
      delete 'remove_from_user'

    end
  end

  resources :requests

  resources :trainings do
    member do
      get 'add_participant'
      get 'del_participant'
    end
  end

  resources :grants do
    member do
      get 'add_participant'
      get 'del_participant'
    end
  end  

  resources :events do
    member do
      get 'add_participant'
      get 'del_participant'
    end
    collection do
      get 'activities'
      get 'not_approved'
      post 'update_index'
      post 'event_status'
      post 'event_delete'
    end
  end

  resources :resumes do
    get 'crop', :on => :member
  end
  put "update_avatar/:id" => "resumes#update_avatar"

  resources :compinfos do
    get 'crop', :on => :member
  end
  put "update_avatar_comp/:id" => "compinfos#update_avatar_comp"
  
  resources :pages

  get 'renew_password' => 'users#renew_password'
  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :sessions => "sessions",
    :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    get "sign_out", :to => "sessions#destroy"
    resources :resumes
    resources :compinfos
  end

  post "valid" => "users#valid"
  post "add_remove_event" => "users#add_remove_event"
  get '/change_emoution' => 'users#change_emoution'
  get 'reset_password/:token' => 'users#reset_password', :as => 'reset_password'
  put 'update_password/:id' => 'users#update_password', :as => 'update_password'
  get 'send_mails'=> 'users#send_mails'
  
  get "/profile" => "users#show"

  match "admin_page", :to => "users#admin_page", :as => :admin_page
  resources :users do #, :only => [:show, :index, :activities ]
    member do
      get "activities"
      get "userevents"      
      get "created_event"
    end
  end

  get "users/sphere", :as => 'sphere'

  root :to => 'events#index' 

  post "/post_find_location" => "connections#post_find_location"

  match '*a', :to => 'errors#routing'
end

app/models/area.rb
# encoding: UTF-8
class Area
  include Mongoid::Document
  field :name, type: String
  has_and_belongs_to_many :users
  has_and_belongs_to_many :grants
  has_and_belongs_to_many :trainings
  has_and_belongs_to_many :events
  validates_uniqueness_of :name, :message => 'Сфера с таким названием уже существует'
end

app/models/training.rb
# -*- encoding : utf-8 -*-
class Training < EventParent
  #belongs_to :user
  #has_many :requests, as: :requestable
  has_and_belongs_to_many :users #participants, class_name: "User", inverse_of: :tractivity
  #belongs_to :user
  field :number, type: Integer


  field :hyperlink, :type => String # Link to external site with/without registration to event
  field :cond # conditions
  field :nation # field as listing
  field :city # may be make as list of the towns
  field :street
  field :building
  field :place
  field :end_date, :type => DateTime
  field :tmp_date, :type => DateTime
  field :tmp_end_date, :type => DateTime
  field :request_date, :type => DateTime #, :type => Array
  field :request_hour, :type => DateTime
  field :employment, :type => Array
  field :areas
  field :employment
  field :salary_type, :type=>Array
  field :direction, :type => Array
  field :x_coordinate, :type => Float
  field :y_coordinate, :type => Float

  field :visible, :type => Boolean

  validates_presence_of :title, :message => 'Обязательно'
  validates_presence_of :description, :message => 'Обязательно'

  has_and_belongs_to_many  :areas
  has_one :image


  accepts_nested_attributes_for :areas, :image


  field :vk
  field :twitter
  field :afisha
  field :fb
  field :cityspb
  field :timepad
  field :lookatme

  validates_format_of :vk, :with => /http:\/\/vk\.com\/.*/, :message => "Неправильный адрес",:allow_blank => true
  validates_format_of :twitter, :with => /http:\/\/(www)?\.twitter\.com\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :afisha, :with => /http:\/\/(www)?\.afisha\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :fb, :with => /http:\/\/(www)?\.facebook\.com\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :timepad, :with => /http:\/\/(.*?)\.timepad\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :lookatme, :with => /http:\/\/(.*?)\.lookatme\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :cityspb, :with => /http:\/\/(www)?\.cityspb\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true


  def self.salary_type
    %w[НЕОПЛАЧИВАЕМАЯ OПЛАЧИВАЕМАЯ]
  end

  def self.employment
    ["НАУЧНЫЕ КОНФЕРЕНЦИЯ" ,"КАРЬЕРНЫЕ СОБЫТИЕ"]
  end

  def user
    User.where(id: self.owner).first
  end

  def tmp_date=(params)
    self.start_date = self.start_date.change(:hour=>params.to_datetime.hour,
                                             :min=>params.to_datetime.min)
    self.end_date = DateTime.new
    self.end_date = self.end_date.change(:year => self.start_date.year,
                                         :month => self.start_date.month,
                                         :day => self.start_date.day)
  end

  def tmp_end_date=(params)
    self.end_date = self.end_date.change(:hour => params.to_datetime.hour,
                                         :min => params.to_datetime.min)
  end

  def request_hour=(params)
    self.request_date = self.request_date.change(:hour => params.to_datetime.hour,
                                                 :min => params.to_datetime.min)
  end


end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  # GET /trainings
  # GET /trainings.json
  # TODO: check - may be we should make before filter

  def index
    @trainings = Training.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trainings }
    end
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @training = Training.find(params[:id])
    #@requests = @training.requests
    @owner = User.find(@training.owner)
    #UserMailer.info_email(current_user).deliver
    respond_to do |format|
      format.html { render :layout => false }# show.html.erb
      format.json { render json: @training }
    end
  end

  # GET /trainings/new
  # GET /trainings/new.json
  def new
    unless params.nil?
      @x = params[:x]
      @y = params[:y]   
    end
    @training = Training.new

    respond_to do |format|
      format.js { render :layout => false }# new.html.erb
      format.json { render json: @training }
    end
  end

  # GET /trainings/1/edit
  def edit
    @training = Training.find(params[:id])
  end

  # POST /trainings
  # POST /trainings.json
  def create
   # puts params.inspect
    @training = Training.new(params[:training])
    @training.write_attributes(owner: current_user.id) unless current_user.nil?
    @malala = 'bfdgfdgdfg2222'
    respond_to do |format|
      if @training.save
        
        # deleting cookie with image id, if it exists
       # cookies.delete :training_image unless cookies[:training_image].nil?
        format.html { redirect_to root_path, notice: 'Training was successfully created.' }
        format.json { render json: @training, status: :created, location: @training }
      else
        format.html { render json: @training.errors }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /trainings/1
  # PUT /trainings/1.json
  def update
    @training = Training.find(params[:id])

    respond_to do |format|
      if @training.update_attributes(params[:training])
        format.html { redirect_to root_url, notice: 'Training was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training = Training.find(params[:id])
    @training.destroy

    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { head :ok }
    end
  end

  def add_participant
    @training = Training.find(params[:id])
    current_user.trainings << @training
    #redirect_to root_url #@training
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
      format.js { status :ok }
    end
  end

  def del_participant
    training = Training.find(params[:id])
    current_user.training_ids.delete(training.id)
    training.user_ids.delete(current_user.id)
    current_user.save   
    training.save   
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end

end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_new.erb
<%= form_for :training, :url => {:action => :create, :controller => :trainings}, :method => :post do |f| %>

    <span class="label">НАЗВАНИЕ</span><%= f.text_field :title, :class => "name" %><span class="error"></span>
    <div class="leftpart">
      <span class="label">ОПИСАНИЕ</span>
      <%= f.text_area :description %>
      <span class="error"></span>
      <div class="clr"></div>
      <span class="label">Вконтакте</span><%= f.text_field :vk, :class=>"text fr", :style=>"width:456px; margin-bottom: 5px;" %><div class="clr"></div>
      <span class="label">Facebook</span><%= f.text_field :facebook, :class=>"text fr", :style=>"width:456px; margin-bottom: 5px;" %><div class="clr"></div>
      <span class="label">Twitter</span><%= f.text_field :twitter, :class=>"text fr", :style=>"width:456px; margin-bottom: 5px;" %><div class="clr"></div>

      <div class="isideleft">
        <span class="label">СТРАНА</span>
        <%= f.text_field :nation, :class => "text fr", :style => "width:260px; margin-bottom: 5px;" %>
        <div class="clr"></div>
        <span class="label">ГОРОД</span>
        <%= f.text_field :city, :class => "text fr", :style => "width:260px; margin-bottom: 5px;" %>
        <div class="clr"></div>
        <span class="label" style="float:left">УЛИЦА</span>

        <div class="fr">
          <%= f.text_field :street, :class => "text fl", :style => "width:187px;" %>
          <span class="label" class="fl" style="margin: 0 5px; float:left;">ДОМ</span>
          <%= f.text_field :building, :class => "text fr", :style => "width:22px;" %>
        </div>
        <span class="label" style="margin-top: 11px;">МЕСТО</span><%= f.text_field :place, :class => "text fr", :style => "width:260px; margin-top: -19px;" %>
        <div class="clr"></div>
      </div>
      <div class="isideright" id="map5" style="position: relative; background-color: rgb(229, 227, 223); overflow: hidden;">
        <script>
            function google_maps5() {
                var latlng = new google.maps.LatLng(49.83209, 23.975322); // Координаты карты
                var settings = {
                    zoom:12, // Выставляем параметры зума для карты
                    center:latlng,
                    mapTypeControl:false,
                    mapTypeControlOptions:{style:google.maps.MapTypeControlStyle.DROPDOWN_MENU},
                    navigationControl:true,
                    navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL},
                    mapTypeId:google.maps.MapTypeId.ROADMAP
                };
                var map = new google.maps.Map(document.getElementById("map5"), settings); // Выбираем див куда ставить карту
                var myLatlng = new google.maps.LatLng(49.83209, 23.975322);  // Координаты маркера
                var myOptions = {
                    zoom:12, // Выставляем параметры зума для маркера
                    center:myLatlng,
                    mapTypeId:google.maps.MapTypeId.ROADMAP
                }
                var map = new google.maps.Map(document.getElementById("map5"), myOptions);  // Выбираем див куда ставить маркер
                var marker = new google.maps.Marker({
                    position:myLatlng,
                    map:map,
                    title:"A"
                });
            }
        </script>

      </div>

      <script type="text/javascript">
          $("#map5init").click(function () {
              google_maps5();
          });

      </script>

      <div class="clr"></div>

      <span class="label">ДАТА</span>

      <div class="datesel300 large_select" style="width: 483px !important;">
        <div class="ficha">
          <%= f.date_select :start_date, :order => [:day, :month, :year] %>
          <span style="margin: 0 8px">С</span>
          <%= f.time_select :tmp_date %>
          <span style="margin: 0 8px">ДО</span>

          <%= f.time_select :tmp_end_date %>

        </div>
      </div>

      <span class="label">ССЫЛКА НА САЙТ ИЛИ РЕГИСТРАЦИЮ</span>
      <%= f.text_field :hyperlink, :class => "siteaddress", :style => "margin-bottom: 5px;" %>
      <div class="clr"></div>

      <span class="label">ПОСЛЕДНИЙ СРОК РЕГИСТРАЦИИ</span>

      <div class="datesel300">
        <%= f.date_select :request_date, :order => [:day, :month, :year] %>

        <div class="ficha">
          <span style="margin: 0 8px">ДО</span>

          <%= f.time_select :request_hour %>

        </div>

      </div>

      <div class="clr"></div>
      <span class="label">СФЕРА:</span>

      <div class="samvup sam1 sampk">
        <div class="all">ВСЕ</div>
        <div class="allCats">
          <script type="text/javascript">
              $(document).ready(function () {
                  $(".catsItem").click(function () {
                      var a = $(this).find(".jqTransformCheckbox").hasClass("jqTransformChecked");
                      if (a) {
                          $(this).find(".descripting").addClass("act");
                      } else {
                          $(this).find(".descripting").removeClass("act");
                      }
                      ;
                  });
              });
          </script>
          <% Area.all.each do |area| %>
              <div class="catsItem">
                <label>
                  <input type="checkbox" name="training[area_ids][]" id="area-<%= area.id %>" value="<%= area.id %>">
                  <span class="descripting"><%= area.name %></span>

                  <div class="clr"></div>
                </label>
              </div>
          <% end %>
        </div>
      </div>


    </div>

    <div class="rightpart">
      <span class="label">ФОТО:</span>

      <div class="photo">
        <%= image_tag "contimg4.png" %>
        <%= fields_for 'training[u_image]' do |img|%>
            <%= img.file_field :photo %>
        <% end %>
        <input type="hidden" name='training[image_id]' id='training_hidden' >
      </div>
    </div>
    <div class="clr"></div>


    <div class="manycheck">
      <div class="pchecks">
        <span class="opl nopaid"><input type="radio" name="training[salary_type]" value="НЕОПЛАЧИВАЕМАЯ">НЕОПЛАЧИВАЕМАЯ</span>
        <span class="opl paid"><input type="radio" name="training[salary_type]" value="ОПЛАЧИВАЕМАЯ">ОПЛАЧИВАЕМАЯ</span>
      </div>
      <div class="clr"></div>
    </div>
    <div class="clr"></div>

    <% if current_user %>
        <% if current_user.role.name == 'admin' %>
            <span class="label" style="float: left; margin-top: 6px;">СТАТУС:</span>
            <div style="margin: 5px 0 0 71px;"><%= f.select :status, options_for_select([["НОВОЕ", "НОВОЕ"], ["УДАЛЕНО", "УДАЛЕНО"], ["ОДОБРЕНО", "ОДОБРЕНО"]]) %></div>
        <% end %>
    <% end %>

    <span class="label fl" style="margin-right: 20px">ЗАНЯТОСТЬ:</span>
    <div class="manycheck">
      <div class="pchecks">
        <% Training.employment.each do |employment| %>
            <span class="opl"><input type="radio" name="training[employment]" value="<%= employment %>"><%= employment %></span>
        <% end %>
      </div>
      <div class="clr"></div>
    </div>

    <div class="add">
      <button type="submit">ДОБАВИТЬ</button>
    </div>
<% end %>
<script>


    $('form[action="/trainings"]').submit(function (e) {
        e.preventDefault();
        $.ajax({
            data:$(this).serialize(),
            type:'post',
            url:'<%= trainings_path %>',
            dataType:'json',
            statusCode:{
                422:function (result) {
                    var response = $.parseJSON(result.responseText);
                    if (response.title)
                        $('#training_title').next('.error').html(response.title[0]).fadeIn();
                    else
                        $('#training_title').next('.error').empty().fadeOut();

                    if (response.description)
                        $('#training_description').next('.error').html(response.description[0]).fadeIn();
                    else
                        $('#training_description').next('.error').empty().fadeOut();

                }
            }

        }).done(function (result) {
//                    if (result) window.location = window.location;
//                    else {
//                        console.log(result);
//                    }
                });
    });
</script>

app/views/trainings/edit.html.erb
<%= render 'form' %>

app/views/trainings/index.html.erb
<h1>Listing trainings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trainings.each do |training| %>
  <tr>
    <td><%= training.title %></td>
    <td><%= training.try(:user) %></td>
    <td><%= link_to 'Show', training %></td>
    <td><%= link_to 'Edit', edit_training_path(training) %></td>
    <td><%= link_to 'Destroy', training, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Training', new_training_path %>

app/views/trainings/new.html.erb
<%= render 'new' %>

app/views/trainings/new.js.erb
$('#insert_coordinates_train').remove();
$("#insert_train_coordinates").before("<div id='insert_coordinates_train'><input id='x_coordinate' name='training[x_coordinate]' size='30' type='hidden' value='<%=@x%>'><input id='y_coordinate' name='training[y_coordinate]' size='30' type='hidden' value='<%=@y%>'></div>");

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>
<div class="trshow">
  <div class="soc_info">
    <% unless @training.timepad.blank? %>
      <div class="inlblck">
        <a href="<%=  @training.timepad %>" target="_blank">
          <%= image_tag "/assets/ltp.png"%>
        </a>  
      </div>
    <% end %>
    <% unless @training.lookatme.blank? %>
      <div class="inlblck">
        <a href="<%=  @training.lookatme %>" target="_blank">
          <%= image_tag "/assets/llookatme.jpg"%>
        </a>  
      </div>
    <% end %>
    <% unless @training.cityspb.blank? %>
      <div class="inlblck">
        <a href="<%=  @training.cityspb %>" target="_blank">
          <%= image_tag "/assets/lcityspb.jpg"%>
        </a>  
      </div>
    <% end %>
    <% unless @training.afisha.blank? %>
      <div class="inlblck">
        <a href="<%=  @training.afisha %>" target="_blank">
          <%= image_tag "/assets/lafisha.jpg"%>
        </a>  
      </div>
    <% end %>
    <% unless @training.vk.blank? %>
      <div class="inlblck">
        <a href="<%=  @training.vk %>" target="_blank">
          <%= image_tag "/assets/lvk.png"%>
        </a>  
      </div>
    <% end %>
    <% unless @training.fb.blank? %>
      <div class="inlblck">
        <a href="<%=  @training.fb %>" target="_blank">
          <%= image_tag "/assets/lfb.png"%>
        </a>
      </div>
    <% end %>
    <% unless @training.twitter.blank? %>
      <div class="inlblck">
        <a href="<%=  @training.twitter %>" target="_blank">
          <%= image_tag "/assets/ltwitter.png"%>
        </a>
      </div>
    <% end %>
  </div>
  <div id="close" onclick="closeItemPopup()">X</div>
  <div class="item_title yellow_letter"> <%= @training.title %> - СТАЖИРОВКА 

<%= render :partial => 'layouts/share' %>
  </div>
  <table class="test">
    <tr>
      <td rowspan="2" valign = "top">
        <div class="eventimage"> 
          <% if @training.photo.blank? %>
            <%= image_tag "/assets/Untitled.jpg" %>
          <% else %>
            <%=image_tag @training.photo.url %> 
          <% end %>
        </div>

         <div>
          
        <%if current_user%>  
          <div class="participant">  
            <%if current_user.training_ids.include?(@training.id)%>  
              <div onclick = "delpart();" data-id="<%= @training.id%>" data-item = "training" data-url="<%= del_participant_training_path(@training)%>"> УДАЛИТЬ ИЗ МОЕГО КАЛЕНДАРЯ </div>
              <!--
                <%= link_to "Удалить", del_participant_training_path(@training)%>
              -->
            <% else %>
              <!--
                <%= link_to "Добавить", add_participant_training_path(@training), :remote => true %>
              -->
              <div onclick = "addpart();" data-id="<%= @training.id%>" data-item = "training" data-url="<%= add_participant_training_path(@training)%>"> ДОБАВИТЬ В МОЙ КАЛЕНДАРЬ </div>
            <% end %>
          </div>
        <% end %>

        </div>
      </td>
      <td colspan="2"> <%= @training.description %> </td>
    </tr>
    <tr>
      <td class="lcolumn2">
        <div> 
          <% @training.salary_type.each do |s| %> 
            <%= s unless s.blank? %>
          <%end%>
        </div>
        <div class="yellow_letter"> C <%= Russian::l @training.start_date, :format => :long %> 
        </br>ДО <%= Russian::l @training.end_date, :format => :long %>
        </div>
        <div class="user_show"> ДОБАВИЛ <p><%= link_to @owner.name, activities_user_path(@owner.id) %></p> </div>

        <div class="item-map" data-x="<%= @training.try(:x_coordinate) || "59.93365223894488" %>" data-y="<%= @training.try(:y_coordinate) || "30.300378486327617"%>"> 
          <div id="geo-map-zone">
            <div style="margin-top: 40px; display: none;" class="fs-inner-box h" id="geomap-info"></div>
            <div id="geo-map" data-x="<%= @training.try(:x_coordinate) || "59.93365223894488"%>" data-y="<%= @training.try(:y_coordinate) || "30.300378486327617"%>" ></div> 
        </div>
      </div>
      </td>
      <td class="rcolumn2">
        <div> 
          <% @training.employment.each do |e| %>
            <%= e unless e.blank? %>
          <%end%> 
        </div>
        <div class = "yellow_letter" > ПОСЛЕДНИЙ СРОК ПОДАЧИ ЗАЯВОК: </div>
        <%= Russian::l @training.request_date, :format => :long %>
        <div> <%= @training.hyperlink %> </div>
        <div> 
          <%= @training.place %> 
          <%= @training.nation %> 
          <%= @training.city %> 
          <%= @training.street %> 
          <%= @training.building %> 
        </div>
      </td>  
    </tr>
  </table>  

  <% if current_user%>
    <% if (current_user.role?(:admin) || current_user.id == @training.owner) %>
      <%= link_to 'Редактировать', edit_training_path(@training) %> |
    <% end %>
  <% end %>
  </br>
</div>