config/routes.rb
TestMongoid::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications
  
   post "/delete_globall" => "connections#set_to_nil"

   get "/create_connection" => "connections#new"

   get "/find_connection" => "connections#find"

    get "/choose" => "connections#choose"

  get "/create_resume_from_social_facebook" => "connections#create_resume_from_social_facebook"

  get "/create_resume_from_social_vk" => "connections#create_resume_from_social_vk"

  get "omniauth_callbacks/facebook"

  mount TinymceFm::Engine => "/tinymce_fm"

  resource :images

  resources :months do
    collection do
      post 'update_calendar'
    end
  end

  resources :areas do
    collection do
      post 'add_to_user'
      get 'list'
      delete 'remove_from_user'

    end
  end

  resources :requests

  resources :trainings do
    member do
      get 'add_participant'
      get 'del_participant'
    end
  end

  resources :grants do
    member do
      get 'add_participant'
      get 'del_participant'
    end
  end  

  resources :events do
    member do
      get 'add_participant'
      get 'del_participant'
    end
    collection do
      get 'activities'
      get 'not_approved'
      post 'update_index'
      post 'event_status'
      post 'event_delete'
    end
  end

  resources :resumes do
    get 'crop', :on => :member
  end
  put "update_avatar/:id" => "resumes#update_avatar"

  resources :compinfos do
    get 'crop', :on => :member
  end
  put "update_avatar_comp/:id" => "compinfos#update_avatar_comp"
  
  resources :pages

  get 'renew_password' => 'users#renew_password'
  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :sessions => "sessions",
    :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    get "sign_out", :to => "sessions#destroy"
    resources :resumes
    resources :compinfos
  end

  post "valid" => "users#valid"
  post "add_remove_event" => "users#add_remove_event"
  get '/change_emoution' => 'users#change_emoution'
  get 'reset_password/:token' => 'users#reset_password', :as => 'reset_password'
  put 'update_password/:id' => 'users#update_password', :as => 'update_password'
  get 'send_mails'=> 'users#send_mails'
  
  get "/profile" => "users#show"

  match "admin_page", :to => "users#admin_page", :as => :admin_page
  resources :users do #, :only => [:show, :index, :activities ]
    member do
      get "activities"
      get "userevents"      
      get "created_event"
    end
  end

  get "users/sphere", :as => 'sphere'

  root :to => 'events#index' 

  post "/post_find_location" => "connections#post_find_location"

  match '*a', :to => 'errors#routing'
end

app/models/area.rb
# encoding: UTF-8
class Area
  include Mongoid::Document
  field :name, type: String
  has_and_belongs_to_many :users
  has_and_belongs_to_many :grants
  has_and_belongs_to_many :trainings
  has_and_belongs_to_many :events
  validates_uniqueness_of :name, :message => 'Сфера с таким названием уже существует'
end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < EventParent
  #has_many :requests, as: :requestable
  #belongs_to :user
  has_and_belongs_to_many :users#, class_name: "User", inverse_of: :evactivity
  field :number, type: Integer

  field :hyperlink, :type => String # Link to external site with/without registration to event
  field :cond # conditions for registrations to the event
  field :areas # area for examples IT, buildings and etc
  field :nation # field as listing
  field :city # may be make as list of the towns
  field :street
  field :building
  field :place
  field :direction, :type => Array
  field :end_date, :type => DateTime
  field :tmp_date, :type => DateTime
  field :tmp_end_date, :type => DateTime
  field :request_date, :type => DateTime
  field :request_hour, :type => DateTime
  field :kind
  field :x_coordinate, :type => Float
  field :y_coordinate, :type => Float
  field :visible, :type => Boolean
  field :payment, :type => Array
  field :area_types, :type => Array

  validates_presence_of :title, :message => 'Обязательно'
  validates_presence_of :description, :message => 'Обязательно'

  mount_uploader :photo, ImageUploader
  

 #after_create :collect_coordinates

  def collect_coordinates
    puts "x"*30
    self.coordinates = Geocoder.coordinates("#{nation}, #{city} ,#{street}, #{building}")
    puts self.coordinates
    puts "x"*30
    self.save
  end

  def self.area_types
    ["НАУЧНЫЕ КОНФЕРЕНЦИИ", "КАРЬЕРНЫЕ СОБЫТИЯ"]
  end

  has_and_belongs_to_many  :areas
  has_one :image

  accepts_nested_attributes_for :areas, :image

  field :vk
  field :twitter
  field :afisha
  field :fb
  field :cityspb
  field :timepad
  field :lookatme

  validates_format_of :vk, :with => /http:\/\/vk\.com\/.*/, :message => "Неправильный адрес",:allow_blank => true
  validates_format_of :twitter, :with => /http:\/\/(www)?\.twitter\.com\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :afisha, :with => /http:\/\/(www)?\.afisha\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :fb, :with => /http:\/\/(www)?\.facebook\.com\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :timepad, :with => /http:\/\/(.*?)\.timepad\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :lookatme, :with => /http:\/\/(.*?)\.lookatme\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :cityspb, :with => /http:\/\/(www)?\.cityspb\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true



 
 


 def self.payment
    %w[НЕОПЛАЧИВАЕМАЯ ОПЛАЧИВАЕМАЯ]
  end

  def tmp_date=(params)
    self.start_date = self.start_date.change(:hour=>params.to_datetime.hour,
                                             :min=>params.to_datetime.min)
    self.end_date = DateTime.new
    self.end_date = self.end_date.change(:year => self.start_date.year,
                                         :month => self.start_date.month,
                                         :day => self.start_date.day)
  end

  def tmp_end_date=(params)
    self.end_date = self.end_date.change(:hour => params.to_datetime.hour,
                                         :min => params.to_datetime.min)
  end

  def request_hour=(params)
    self.request_date = self.request_date.change(:hour => params.to_datetime.hour,
                                                 :min => params.to_datetime.min)
  end

end

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
require 'will_paginate/array'
class EventsController < ApplicationController
  include EventsHelper

  load_and_authorize_resource

  def index
    @event_id = params[:event_id]
    @trainings_odobreno = Training.where(:status=>'ОДОБРЕНО', :request_date => {'$gte' => Time.now})
    @grants_odobreno = Grant.where(:status=>'ОДОБРЕНО', :start_date => {'$gte' => Time.now})
    @events_odobreno = Event.where(:status=>'ОДОБРЕНО', :request_date => {'$gte' => Time.now})
    
  @events = []
  existing_ids = []      
    
    if params[:grant]      
      @grants = Grant.where(:status=>'ОДОБРЕНО')
      @grants = @grants.in(:area_ids=>params[:grant][:areas]) if params[:grant][:areas]
      @grants = @grants.where(:direction=>params[:grant][:direction]) if params[:grant][:direction]
    end# unless params[:check_grant].nil?

    if params[:event]
      @evs = Event.where(:status=>'ОДОБРЕНО')
      @evs = @evs.in(:area_ids=>params[:event][:areas]) if params[:event][:areas]
      @evs = @evs.in(:area_types=>params[:event][:area_types]) if params[:event][:area_types]
      
    end #unless params[:check_event].nil?

    if params[:training]
      @trainings = Training.where(:status=>'ОДОБРЕНО')
      @trainings = @trainings.in(:area_ids=>params[:training][:areas]) if params[:training][:areas]
      @trainings = @trainings.in(:salary_type => params[:training][:payments]) if params[:training][:payments]
      @trainings = @trainings.in(:owner => params[:training][:compinfos]) if params[:training][:compinfos]

    end #unless params[:check_training].nil?
  

  if not params[:month].nil? or not cookies[:month].blank?         
     month = params[:month].to_i
     year = params[:year].to_i
     now = DateTime.now.change(:day => 1, :month => month + 1, :year=> year)
     @trainings = Training.where(:status=>'ОДОБРЕНО') if @trainings.nil?
     @trainings = @trainings.where(:start_date => {'$gte' => now.beginning_of_month,'$lt' => now.end_of_month}) if params[:check_training].nil?
    

     @evs = Event.where(:status=>'ОДОБРЕНО') if @evs.nil?
     @evs = @evs.where(:start_date => {'$gte' => now.beginning_of_month,'$lt' => now.end_of_month}) if params[:check_event].nil?
    

     @grants = Grant.where(:status=>'ОДОБРЕНО') if @grants.nil?
     @grants = @grants.where(:start_date => {'$gte' => now.beginning_of_month,'$lt' => now.end_of_month}) if params[:check_grant].nil?
    
     cookies[:month] = params[:month]   
      
     if not params[:month].eql?('undefined')
       month = params[:month].to_i
       year = params[:year].to_i
       now = DateTime.now.change(:day => 1, :month => month + 1, :year=> year)
       
       @trainings = Training.where(:status=>'ОДОБРЕНО') if @trainings.nil?
       unless params[:check_training].nil?
        @trainings = @trainings.where(:start_date => {'$gte' => now.beginning_of_month,'$lt' => now.end_of_month})
       else
        @trainings =[]
       end
             
       @evs = Event.where(:status=>'ОДОБРЕНО') if @evs.nil?
       unless params[:check_event].nil?
        @evs = @evs.where(:start_date => {'$gte' => now.beginning_of_month,'$lt' => now.end_of_month})
       else
        @evs = []
       end

       @grants = Grant.where(:status=>'ОДОБРЕНО') if @grants.nil?
       unless params[:check_grant].nil?
        @grants = @grants.where(:start_date => {'$gte' => now.beginning_of_month,'$lt' => now.end_of_month}) 
       else
        @grants = []
       end
      
       cookies[:month] = params[:month]
        

     end
  end  
  
  years = %w[2012 2013]
  months =  %w[jan feb mar apr may june july aug sept oct nov dec]
  years.each do |year|      
      months.each_with_index do |month, index|        
        if Grant.month(index, year.to_i).count > 0 || Event.month(index, year.to_i).count > 0 || Training.month(index, year.to_i).count > 0
          
          @events << Month.new(:number=>index, :name=>month)           
          Grant.month(index, year.to_i).each do |grant|           
            if @grants.nil?
              
              @events << grant
              grant.visible = true
              existing_ids << grant.id
            else            
              @events << grant # if @grants.include?(grant)
              existing_ids << grant.id if @grants.include?(grant)
              grant.visible = true if @grants.include?(grant)
            end          
          end #if params[:check_grant].nil?

          Event.month(index, year.to_i).each do |event|            
            if @evs.nil?
              @events << event
              event.visible = true
              existing_ids << event.id
            else
              @events << event # if @grants.include?(grant)
              existing_ids << event.id if @evs.include?(event)
              event.visible = true if @evs.include?(event)
            end
          end #if params[:check_event].nil?

          Training.month(index, year.to_i).each do |training|
            if @trainings.nil?
              @events << training
              training.visible = true
              existing_ids << training.id
            else

              @events << training # if @grants.include?(grant)
              existing_ids << training.id if @trainings.include?(training)
              training.visible = true if @trainings.include?(training)
            end
          end #if params[:check_training].nil?        
        end
      end      
    end
    @events = sort_array_events(@events)
    
    if @events.count == 0
        months.each_with_index do |month, index|
        @events << Month.new(:number=>index, :name=>month)
       end
    end 

  @events = @events.paginate(:page => params[:page], :per_page => 12)

  existing_ids.each do |event|
    params[:grants].delete event.to_s if not params[:grants].nil? and params[:grants].include?(event.to_s)
  end


  @ids_to_show = []


  ### Getting grant ids which will fade in
  existing_ids.each do |event|
    @ids_to_show << event.to_s if not params[:grants].nil? and not params[:grants].include?(event.to_s)
  end


  ### Getting grant ids which will fade out
  @ids_to_delete = []
  unless params[:grants].nil?
    params[:grants].each do |grant|
      @ids_to_delete << grant
    end
  end

  unless params[:trainings].nil?
    params[:trainings].each do |training|
      @ids_to_delete << training
    end
  end

  unless params[:events].nil?
    params[:events].each do |event|
      @ids_to_delete << event
    end
  end  
  
    respond_to do |format|
      format.html
      format.json { render json: { delete:@ids_to_delete, show:@ids_to_show } }
      format.xml { render xml: @items }
      format.js
    end
  end


  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @owner = User.find(@event.owner)
    respond_to do |format|
      format.html { render :layout => false }# show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    unless params.nil?
      @x = params[:x]
      @y = params[:y]   
    end
    @event = Event.new

    respond_to do |format|
      format.js { render :layout => false }# new.html.erb
      format.json { render json: @event }
    end
    
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    @event.write_attributes(owner: current_user.id) unless current_user.nil?

    respond_to do |format|
      if @event.save
        # deleting cookie with image id, if it exists
        cookies.delete :event_image unless cookies[:event_image].nil?
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render json: @event.errors }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to root_url, notice: 'Training was successfully updated.'}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end

  def add_participant
    event = Event.find(params[:id])
    current_user.events << event
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
      format.js { status :ok }
    end
  end

  def del_participant
    event = Event.find(params[:id])
    current_user.event_ids.delete(event.id)
    event.user_ids.delete(current_user.id)
    current_user.save   
    event.save   
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end

  def not_approved

    #@items = []
    
    #@items += Training.any_in(:status => [nil, "УДАЛЕНО", "НОВОЕ"]).where(:start_date.gte => DateTime.now).all.to_a
    #logger.debug @items
    #@items += Event.any_in(:status => [nil, "УДАЛЕНО", "НОВОЕ"]).where(:start_date.gte => DateTime.now).all.to_a
    #logger.debug @items
    #@items += Grant.any_in(:status => [nil, "УДАЛЕНО", "НОВОЕ"]).where(:start_date.gte => DateTime.now).all.to_a
    @count = EventParent.any_in(:status => [nil, "УДАЛЕНО", "НОВОЕ"]).count
    @items = EventParent.any_in(:status => [nil, "УДАЛЕНО", "НОВОЕ"])
    
    unless @items.blank?
      @items.sort!{|x,y| x.start_date <=> y.start_date} if @items.length > 1
    end 
    
    respond_to do |format|

app/helpers/events_helper.rb
module EventsHelper
	def sort_array_events(array_events)
		new_array = []
		arr = []
		array_events.each do |event|
			if not event.class.name.eql?('Month')
				arr += event.to_a
			 else
			 	arr.sort_by! {|e| e.start_date}				
			 	new_array += arr
			 	new_array += event.to_a
			 	arr = []
			end
		end		
		arr.sort_by! {|e| e.start_date}		
		new_array += arr
	end
end

app/views/events/_form.html.erb
<%= simple_form_for @event, :validate => true  do |f| %>
  <div id="close" onclick="closeItemPopup()">X</div>
  <div class="name_form">ЯРМАРКА ppppppВАКАНСИЙ, ПРЕЗЕНТАЦИЯ, МАСTЕР-КЛАСС, КЕЙС-ТУРНИР, КОНФЕРЕНЦИЯ</div>

  
<%= link_to "Find Place", find_event_path, id: "find_place"%>
  
  <%= f.input :title, :label => "НАЗВАНИЕ", :wrapper_html => { :class => 'first_field' } %>
  <div id="geo-map-zone">
    <div id="search-area" class="h" style="">
        <input type="text" value="" class="form-input search-address">
        <a class="btn1 btn-mini search-btn">Поиск</a>
    </div>
    <div style="margin-top: 40px; display: none;" class="fs-inner-box h" id="geomap-info"></div>
    <div id="geo-map" onhover="alert(1)"></div> </div>
  <%= f.input :description, :as => :text, :label => "ОПИСАНИЕ", :input_html => {:rows => "8", :cols => "55"} %>
  <%= f.input :photo, :label => "КАРТИНКА"  %>
  <%= f.input :nation, :label => "СТРАНА"  %>
  <%= f.input :city, :label => "ГОРОД"  %>
  <%= f.input :street, :label => "УЛИЦА", :wrapper_html => { :class => 'strt' } %>
  <%= f.input :building, :label => "ДОМ", :wrapper_html => { :class => 'house' } %>
  <%= f.input :place, :label => "МЕСТО"  %>
  <%= f.input :start_date, :label => "НАЧАЛО" , :as => :datetime %>
  <%= f.input :end_date, :label => "КОНЕЦ" , :as => :datetime %>
  <%= f.input :hyperlink, :label => "ССЫЛКА НА САЙТ ИЛИ РЕГИСТРАЦИЮ",:wrapper_html => {:class => 'hprlnk'} %>
  <div class="weblinks">
    <div id="socimgs">
      <div class="inlblck hprlnk">
        ССЫЛКИ НА МЕРОПРИЯТИЯ НА СЕРВИСАХ: 
      </div>
      <div class="inlblck">
        <%= image_tag "/assets/ltp.png", :onclick => "itemshow('timepad');"%>
      </div>
      <div class="inlblck">
        <%= image_tag "/assets/llookatme.jpg", :onclick => "itemshow('lookatme');"%>
      </div>
      <div class="inlblck">
        <%= image_tag "/assets/lcityspb.jpg", :onclick => "itemshow('cityspb');"%>
      </div>
      <div class="inlblck">
        <%= image_tag "/assets/lafisha.jpg", :onclick => "itemshow('afisha');"%>
      </div>
      <div class="inlblck">
        <%= image_tag "/assets/lvk.png", :onclick => "itemshow('vk');"%>
      </div>
      <div class="inlblck">
        <%= image_tag "/assets/lfb.png", :onclick => "itemshow('fb');"%>
      </div>
      <div class="inlblck">
        <%= image_tag "/assets/ltwitter.png", :onclick => "itemshow('twitter');"%>
      </div>
    </div>


      <% if @event.timepad %>
        <div class="fields timepad">
      <% else %>
        <div class="fields timepad" style="display: none;">
      <% end %>
        <div class="inlblck">
          <%= image_tag "/assets/ltp.png"%>
        </div>
        <%= f.input :timepad, :label => false, :placeholder => 'Укажите ссылку на мероприятие на выбранном сервисе'  %>
      </div>

      <% if @event.lookatme %>
        <div class="fields lookatme">
      <% else %>
        <div class="fields lookatme" style="display: none;">
      <% end %>
        <div class="inlblck">
          <%= image_tag "/assets/llookatme.jpg"%>
        </div>
        <%= f.input :lookatme, :label => false, :placeholder => 'Укажите ссылку на мероприятие на выбранном сервисе'  %>
      </div>

      <% if @event.cityspb %>
        <div class="fields cityspb">
      <% else %>
        <div class="fields cityspb" style="display: none;">
      <% end %>
        <div class="inlblck">
          <%= image_tag "/assets/lcityspb.jpg"%>
        </div>
        <%= f.input :cityspb, :label => false, :placeholder => 'Укажите ссылку на мероприятие на выбранном сервисе'  %>
      </div>

      <% if @event.afisha %>
        <div class="fields afisha">
      <% else %>
        <div class="fields afisha" style="display: none;">
      <% end %>
        <div class="inlblck">
          <%= image_tag "/assets/lafisha.jpg"%>
        </div>
        <%= f.input :afisha, :label => false, :placeholder => 'Укажите ссылку на мероприятие на выбранном сервисе'  %>
      </div>


      <% if @event.vk %>
        <div class="fields vk">
      <% else %>
        <div class="fields vk" style="display: none;">
      <% end %>
        <div class="inlblck">
          <%= image_tag "/assets/lvk.png"%>
        </div>
        <%= f.input :vk, :label => false, :placeholder => 'Укажите ссылку на мероприятие на выбранном сервисе'  %>
      </div>

      <% if @event.fb %>
        <div class="fields fb">
      <% else %>
        <div class="fields fb" style="display: none;">
      <% end %>
        <div class="inlblck">
          <%= image_tag "/assets/lfb.png"%>
        </div>
        <%= f.input :fb, :label => false, :placeholder => 'Укажите ссылку на мероприятие на выбранном сервисе'  %>
      </div>

      <% if @event.twitter %>
        <div class="fields twitter">
      <% else %>
        <div class="fields twitter" style="display: none;">
      <% end %>
        <div class="inlblck">
          <%= image_tag "/assets/ltwitter.png"%>
        </div>
        <%= f.input :twitter, :label => false, :placeholder => 'Укажите ссылку на мероприятие на выбранном сервисе'  %>
      </div>

  </div>
  
  <%= f.input :request_date, :label => "СРОК ПОДАЧИ ЗАЯВОК" , :as => :datetime %>
  <div class="area-label-name">СФЕРА</div>
  <div class="select">
    <div id="evcreateclick" class="area-label" onclick="areashow();">ВСЕ</div>
    <div class="dropdown ardec" onclick="$(event).stopPropagation();">  
      <div class="drop-area-label">ВСЕ</div>
      <%= f.input :areas, :label =>false, :collection => Area.all, :as => :check_boxes, :required => false, :input_html => {:checked=> true, :onclick => "doCheckbox($(this));"}, :wrapper_html => {:class => 'evshadow' } %>
    </div>  
  </div>

  <%= f.input :kind, :label => "" , :collection => ["НАУЧНАЯ КОНФЕРЕНЦИЯ", "КАРЬЕРНОЕ СОБЫТИЕ" ], :as => :check_boxes %>
  <% if current_user%>
    <% if current_user.role?(:admin) %>
      <%= f.input :status, :label => "СТАТУС", :collection => ["НОВОЕ", "УДАЛЕНО", "ОДОБРЕНО" ],:wrapper_html=> { :class => "status_select"}%>
    <% end %>
  <% end %>
  <div class="not-visible">
    <%= f.input :x_coordinate, :label => false %>
    <%= f.input :y_coordinate, :label => false %>  
  </div>

  <%= f.button :submit, :value => "ДОБАВИТЬ" %>


<% end %>

app/views/events/_items.html.erb
<div id="items">
  <%= render @items %>
 
</div>
<%= will_paginate @items %>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.js.erb
$('.monih12').append("<%= j render(@events) %>");
<% if @events.next_page %>
	$(".pagination").replaceWith("<%= j will_paginate(@events) %>");
<% else %>
	$(".pagination").hide();
<% end %>
<% sleep 0.5 %>
$(".moncon").filter(function(){
    return !$(this).children(':first').is('img');
}).click(popup);

$(".close_popup").click(function (e) {
    $('.bbg').removeClass('bbgvisible');
    $(this).parent(".pk_popup").fadeOut(600);

    e.stopPropagation();
});

app/views/events/new.html.erb
<%= render 'new' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="evshow">
  <div class="soc_info">
    <% unless @event.timepad.blank? %>
      <div class="inlblck">
        <a href="<%=  @event.timepad %>" target="_blank">
          <%= image_tag "/assets/ltp.png"%>
        </a>  
      </div>
    <% end %>
    <% unless @event.lookatme.blank? %>
      <div class="inlblck">
        <a href="<%=  @event.lookatme %>" target="_blank">
          <%= image_tag "/assets/llookatme.jpg"%>
        </a>  
      </div>
    <% end %>
    <% unless @event.cityspb.blank? %>
      <div class="inlblck">
        <a href="<%=  @event.cityspb %>" target="_blank">
          <%= image_tag "/assets/lcityspb.jpg"%>
        </a>  
      </div>
    <% end %>
    <% unless @event.afisha.blank? %>
      <div class="inlblck">
        <a href="<%=  @event.afisha %>" target="_blank">
          <%= image_tag "/assets/lafisha.jpg"%>
        </a>  
      </div>
    <% end %>
    <% unless @event.vk.blank? %>
      <div class="inlblck">
        <a href="<%=  @event.vk %>" target="_blank">
          <%= image_tag "/assets/lvk.png"%>
        </a>  
      </div>
    <% end %>
    <% unless @event.fb.blank? %>
      <div class="inlblck">
        <a href="<%=  @event.fb %>" target="_blank">
          <%= image_tag "/assets/lfb.png"%>
        </a>
      </div>
    <% end %>
    <% unless @event.twitter.blank? %>
      <div class="inlblck">
        <a href="<%=  @event.twitter %>" target="_blank">
          <%= image_tag "/assets/ltwitter.png"%>
        </a>
      </div>
    <% end %>
  </div>
  <div id="close" onclick="closeItemPopup()">X</div>
	<div class="item_title green_letter"><%= @event.title %> - СОБЫТИЕ 
  <%= render :partial => 'layouts/share' %>

  </div>
  <table><tr>
    <td class="lcolumn">
      <div class="evimage"> 
        <% if @event.photo.blank? %>
          <%= image_tag "/assets/Untitled2.jpg" %>
        <% else %>
          <%=image_tag @event.photo.url %> 
        <% end %>
      </div>

      <%if current_user%>  
        <div class="participant">  
          <%if current_user.event_ids.include?(@event.id)%>  
            <div onclick = "delpart();" data-id="<%= @event.id%>" data-item = "event" data-url="<%= del_participant_event_path(@event)%>" style="font-size: 20px;"> УДАЛИТЬ ИЗ МОЕГО КАЛЕНДАРЯ </div>
            <!--
              <%= link_to "Удалить", del_participant_event_path(@event)%>
            -->
          <% else %>
            <!--
              <%= link_to "Добавить", add_participant_event_path(@event), :remote => true %>
            -->
            <div onclick = "addpart();" data-id="<%= @event.id%>" data-item = "event" data-url="<%= add_participant_event_path(@event)%>" style="font-size: 20px;"> ДОБАВИТЬ В МОЙ КАЛЕНДАРЬ </div>
          <% end %>
        </div>
      <% end %>

      <div class="green_letter"> C <%= Russian::l @event.start_date, :format => :long %></br>
       ДО <%= Russian::l @event.end_date, :format => :long %> </div>
  		<div> ДОБАВИЛ:  <%= link_to @owner.email, activities_user_path(@owner.id) %> </div>
  		<div> 
  			<%= @event.place %> 
  			<%= @event.nation %> 
  			<%= @event.city %> 
  			<%= @event.street %> 
  			<%= @event.building %> 
  		</div>
    </td>
    <td class="rcolumn">
      <div> <%= @event.description %> </div>
      <div class="green_letter"> СРОК ПОДАЧИ ЗАЯВОК <%= Russian::l @event.request_date, :format => :long %> </div>
      <div> <%= @event.hyperlink %> </div>
      <div class="item-map" data-x="<%= @event.try(:x_coordinate) || "59.93365223894488" %>" data-y="<%= @event.try(:y_coordinate) || "30.300378486327617"%>"> 
        <div id="geo-map-zone">
          <div style="margin-top: 40px; display: none;" class="fs-inner-box h" id="geomap-info"></div>
          <div id="geo-map" data-x="<%= @event.try(:x_coordinate) || "59.93365223894488"%>" data-y="<%= @event.try(:y_coordinate) || "30.300378486327617"%>" ></div> 
        </div>
      </div>
    </td>  
  </tr>
  </table>  

<% if current_user%>
  <% if (current_user.role?(:admin) || current_user.id == @event.owner) %>
    <%= link_to 'редактировать', edit_event_path(@event) %> |
  <% end %>
<% end %>