config/routes.rb
TestMongoid::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications
  
   post "/delete_globall" => "connections#set_to_nil"

   get "/create_connection" => "connections#new"

   get "/find_connection" => "connections#find"

    get "/choose" => "connections#choose"

  get "/create_resume_from_social_facebook" => "connections#create_resume_from_social_facebook"

  get "/create_resume_from_social_vk" => "connections#create_resume_from_social_vk"

  get "omniauth_callbacks/facebook"

  mount TinymceFm::Engine => "/tinymce_fm"

  resource :images

  resources :months do
    collection do
      post 'update_calendar'
    end
  end

  resources :areas do
    collection do
      post 'add_to_user'
      get 'list'
      delete 'remove_from_user'

    end
  end

  resources :requests

  resources :trainings do
    member do
      get 'add_participant'
      get 'del_participant'
    end
  end

  resources :grants do
    member do
      get 'add_participant'
      get 'del_participant'
    end
  end  

  resources :events do
    member do
      get 'add_participant'
      get 'del_participant'
    end
    collection do
      get 'activities'
      get 'not_approved'
      post 'update_index'
      post 'event_status'
      post 'event_delete'
    end
  end

  resources :resumes do
    get 'crop', :on => :member
  end
  put "update_avatar/:id" => "resumes#update_avatar"

  resources :compinfos do
    get 'crop', :on => :member
  end
  put "update_avatar_comp/:id" => "compinfos#update_avatar_comp"
  
  resources :pages

  get 'renew_password' => 'users#renew_password'
  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :sessions => "sessions",
    :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    get "sign_out", :to => "sessions#destroy"
    resources :resumes
    resources :compinfos
  end

  post "valid" => "users#valid"
  post "add_remove_event" => "users#add_remove_event"
  get '/change_emoution' => 'users#change_emoution'
  get 'reset_password/:token' => 'users#reset_password', :as => 'reset_password'
  put 'update_password/:id' => 'users#update_password', :as => 'update_password'
  get 'send_mails'=> 'users#send_mails'
  
  get "/profile" => "users#show"

  match "admin_page", :to => "users#admin_page", :as => :admin_page
  resources :users do #, :only => [:show, :index, :activities ]
    member do
      get "activities"
      get "userevents"      
      get "created_event"
    end
  end

  get "users/sphere", :as => 'sphere'

  root :to => 'events#index' 

  post "/post_find_location" => "connections#post_find_location"

  match '*a', :to => 'errors#routing'
end

app/models/area.rb
# encoding: UTF-8
class Area
  include Mongoid::Document
  field :name, type: String
  has_and_belongs_to_many :users
  has_and_belongs_to_many :grants
  has_and_belongs_to_many :trainings
  has_and_belongs_to_many :events
  validates_uniqueness_of :name, :message => 'Сфера с таким названием уже существует'
end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < EventParent
  #has_many :requests, as: :requestable
  #belongs_to :user
  has_and_belongs_to_many :users#, class_name: "User", inverse_of: :evactivity
  field :number, type: Integer

  field :hyperlink, :type => String # Link to external site with/without registration to event
  field :cond # conditions for registrations to the event
  field :areas # area for examples IT, buildings and etc
  field :nation # field as listing
  field :city # may be make as list of the towns
  field :street
  field :building
  field :place
  field :direction, :type => Array
  field :end_date, :type => DateTime
  field :tmp_date, :type => DateTime
  field :tmp_end_date, :type => DateTime
  field :request_date, :type => DateTime
  field :request_hour, :type => DateTime
  field :kind
  field :x_coordinate, :type => Float
  field :y_coordinate, :type => Float
  field :visible, :type => Boolean
  field :payment, :type => Array
  field :area_types, :type => Array

  validates_presence_of :title, :message => 'Обязательно'
  validates_presence_of :description, :message => 'Обязательно'

  mount_uploader :photo, ImageUploader
  

 #after_create :collect_coordinates

  def collect_coordinates
    puts "x"*30
    self.coordinates = Geocoder.coordinates("#{nation}, #{city} ,#{street}, #{building}")
    puts self.coordinates
    puts "x"*30
    self.save
  end

  def self.area_types
    ["НАУЧНЫЕ КОНФЕРЕНЦИИ", "КАРЬЕРНЫЕ СОБЫТИЯ"]
  end

  has_and_belongs_to_many  :areas
  has_one :image

  accepts_nested_attributes_for :areas, :image

  field :vk
  field :twitter
  field :afisha
  field :fb
  field :cityspb
  field :timepad
  field :lookatme

  validates_format_of :vk, :with => /http:\/\/vk\.com\/.*/, :message => "Неправильный адрес",:allow_blank => true
  validates_format_of :twitter, :with => /http:\/\/(www)?\.twitter\.com\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :afisha, :with => /http:\/\/(www)?\.afisha\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :fb, :with => /http:\/\/(www)?\.facebook\.com\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :timepad, :with => /http:\/\/(.*?)\.timepad\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :lookatme, :with => /http:\/\/(.*?)\.lookatme\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true
  validates_format_of :cityspb, :with => /http:\/\/(www)?\.cityspb\.ru\/.*/, :message => "Неправильный адрес", :allow_blank => true



 
 


 def self.payment
    %w[НЕОПЛАЧИВАЕМАЯ ОПЛАЧИВАЕМАЯ]
  end

  def tmp_date=(params)
    self.start_date = self.start_date.change(:hour=>params.to_datetime.hour,
                                             :min=>params.to_datetime.min)
    self.end_date = DateTime.new
    self.end_date = self.end_date.change(:year => self.start_date.year,
                                         :month => self.start_date.month,
                                         :day => self.start_date.day)
  end

  def tmp_end_date=(params)
    self.end_date = self.end_date.change(:hour => params.to_datetime.hour,
                                         :min => params.to_datetime.min)
  end

  def request_hour=(params)
    self.request_date = self.request_date.change(:hour => params.to_datetime.hour,
                                                 :min => params.to_datetime.min)
  end

end

app/controllers/areas_controller.rb
#encoding: UTF-8
class AreasController < ApplicationController
  before_filter :admin_only, :except => [:index, :list, :add_to_user]
  before_filter :load_count

  # GET /areas
  # GET /areas.json

  def load_count
    @count = EventParent.any_in(:status => [nil, "УДАЛЕНО", "НОВОЕ"]).count
  end

  def index
    @title = "Интересующие сферы"
    return redirect_to root_path unless current_user
    @areas = Area.all
    @myareas = current_user.area_ids
    @mydirections = current_user.directions
    @available = current_user.available_areas
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  def list
    @arealist = Area.all
    respond_to do |format|
      format.html 
    end
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @area = Area.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/new
  # GET /areas/new.json
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Сфера "' + @area.name + '" успешно создана' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /areas/1
  # PUT /areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to @area, notice: 'Сфера "' + @area.name + '". успешно отредактирована' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { render json:true }
      format.json { head :ok }
    end
  end

  def add_to_user

    current_user.area_ids = params[:areas]
    current_user.directions = params[:directions]
    current_user.save(:validate => false)
    render :json => true
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_admin_panel.html.erb
<h3>Страница Администратора</h1>
	</br>
	<%= link_to "CФЕРЫ", list_areas_path %> |
	<%= link_to "НЕОДОБРЕННЫЕ МЕРОПРИЯТИЯ (#{count})", not_approved_events_path %> |
<%= link_to "РЕДАКТИРОВАНИЕ СТРАНИЦ", pages_path %>
</br>
<script>
$(function () {
                $('.fjqtrans, .catsItem, .pchecks').jqTransform();
            });
</script>

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <div class="field">
    <%= f.label "Название" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Отправить" %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<div id='content'>
	<%= render 'admin_panel', :count => @count%>
	<%= render 'form' %>

	<%= link_to 'К списку сфер', list_areas_path %>
</div>

app/views/areas/index.html.erb
<div id="content">
  <%if current_user.role == "admin"%>
    <%= render 'admin_panel', :count => @count%>
  <%end%>
  <div id="sphere_used">
    <% current_user.areas.each do |area| %>
        <div class="su">
          <div class="ex"></div>
          <span><%= area.name %></span>
          <input type="hidden" name="areas[]" value="<%= area.id %>"/>
        </div>
    <% end %>
    <% current_user.directions.each do |direction| %>
        <div class="su">
          <div class="ex"></div>
          <span><%= direction %></span>
          <input type="hidden" name="directions[]" value="<%= direction %>"/>
        </div>
    <% end unless current_user.directions.nil? %>
    <div class="su" style="display: none;">
      <div class="ex"></div>
      <span></span>
      <input type="hidden" name="areas[]"/>
    </div>

    <div class="clr"></div>
  </div>
  <%= javascript_include_tag 'jquery.jqtransform' %>
  <script language="javascript">
      $(function(){
          $('#sphere_available, .fjqtrans, .catsItem, .pchecks').jqTransform();
      });
  </script>
  <div id="sphere_available">
        <ul>
          <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;СФЕРЫ:</li>
          <% current_user.available_areas.each do |area| %>
              <% unless current_user.area_ids.include?(area.id) %>
                  <li><input type="checkbox" name="areas[]" value="<%= area.id %>">
                    <label for="areas[<%= area.id %>]"><%= area.name %></label></li>
              <% end %>
        <% end %>
        </ul>
  </div>
  <div class="clr"></div>
</div>
<script>
    $(function () {
        var $checkbox = $('<li><input type="checkbox"></span><label></label></li>');
        var $area = $('.su:last').clone();
        var $fields = $('.su').parent();
        $('#sphere_available .jqTransformCheckbox').click(create_area);
        $('.ex').click(exit_handler);

        function exit_handler() {
            var $this = $(this).parent().clone();
            $fields = $(this).parent().parent();
            $(this).parent().fadeOut(function () {
                $(this).remove();
                $.ajax({
                    data: get_data(),
                    url: '<%= add_to_user_areas_path %>',
                    type: 'post',
                    beforeSend: get_csrf
                }).done(function (result) {
                            if (result == true) {
                                make_checkbox($this)
                            }
                        })
            });
            // TODO: Add animation

            function make_checkbox($input) {
                var $dummy_checkbox = $checkbox.clone();
                var id = $input.children(':last').val();
                var value = $input.children(':eq(1)').html();
                var name = $input.children(':last').attr('name');

                $dummy_checkbox.children(':first').val(id);
                $dummy_checkbox.children(':first').attr('id', id);
                $dummy_checkbox.children(':first').attr('name', name);
                $dummy_checkbox.children(':last').html(value);
                // $dummy_checkbox.children(':last').attr('for', id);
                $dummy_checkbox.jqTransform();
                var $hidden = $dummy_checkbox.children().children('.jqTransformCheckbox');
                $hidden.click(create_area);
                name = $dummy_checkbox.children(':first').children(':last').attr('name');
                if(name == 'areas[]')
                    $('#sphere_available ul:first li:first').after($dummy_checkbox);
                else
                    $('#sphere_available ul:eq(1) li:first').after($dummy_checkbox);
            }
            function get_data() {
                return $fields.children().children('input[type=hidden]').serialize()
            }
        }

        function create_area(e) {
            var $this = $(this);

            $.ajax({
                data: $('#sphere_available input').serialize() + '&' + get_data(),
                url: '<%= add_to_user_areas_path %>',
                type: 'post',
                beforeSend: get_csrf
            }).done(function (result) {
                        if ($this.hasClass('jqTransformChecked') || $this.children('jqTransformChecked').size() > 0) {
                                $this.parent().parent().fadeOut(function () {
                                $(this).remove();
                                $area.children().eq(1).html($this.parent().next().html());
                                // $area.children(':last').attr('name', );
                                $area.children(':last').val(
                                        $this.parent().children(':last').val()
                                );
                                $area.children(':last').attr('name',
                                        $this.parent().children(':last').attr('name')
                                );
                                console.log($this.parent().children(':last'));
                                // console.log($area.children(':last'));

                                $('.su:last').after($area.clone().children(':first').click(exit_handler).parent().css('display', 'block'))
                            })
                        }
                    });

            function get_data() {
                return $fields.children().children('input[type=hidden]').serialize()
            }
        }
    });

    function get_csrf(jqXHR, settings) {
        jqXHR.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
    }
</script>

app/views/areas/list.html.erb
<%= javascript_include_tag :defaults %>
<div id='content'>
  <%= render 'admin_panel', :count => @count%>
  <h1>Список существующих сфер</h1>

  <table class="al" id="arealist" >
      <% @arealist.each do |area| %>
        <tr>
            <td><%= area.name %> &nbsp</td>
            <td><%= link_to "Редактировать", edit_area_path(area) %>&nbsp</td>
            <td><%= link_to "Удалить", area, :class=>'delete' %>&nbsp</td>

          </tr>


        <br/>
      <% end %>
  </table>
  <br />
  <% if current_user%>
    <% if current_user.role?(:admin) %>
      <%= link_to 'Добавить новую сферу', new_area_path %>
    <% end %>
  <% end %>
</div>
<script>
    jQuery(function($) { // document ready

        $('a.delete').live('click', function(event) {
            event.preventDefault();
            var $row = $(this).parent().parent();
            var $link = $(this).attr('href');
            if(confirm('Вы уверены, что хотите удалить сферу?')){
                $.ajax({
                    url: $link, type: 'delete', beforeSend:function(jqXHR, settings) {
                        jqXHR.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
                    }
                }).done(function(){
                            $row.fadeOut();
                        });
            }
        });
    });
</script>

app/views/areas/new.html.erb
<div id='content'>
	<%= render 'admin_panel', :count => @count%>
	<h1>Новая сфера</h1>
	<%= render 'form' %>
	<%= link_to 'К списку сфер', list_areas_path %>
</div>

app/views/areas/show.html.erb
<div id='content'>
	
    <%= render 'admin_panel', :count => @count%>
  	
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Название:</b>
	  <%= @area.name %>
	</p>


	<%= link_to 'Редактировать', edit_area_path(@area) %> |
	<%= link_to 'К списку сфер', list_areas_path %>
</div>