config/routes.rb
TestMongoid::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications
  
   post "/delete_globall" => "connections#set_to_nil"

   get "/create_connection" => "connections#new"

   get "/find_connection" => "connections#find"

    get "/choose" => "connections#choose"

  get "/create_resume_from_social_facebook" => "connections#create_resume_from_social_facebook"

  get "/create_resume_from_social_vk" => "connections#create_resume_from_social_vk"

  get "omniauth_callbacks/facebook"

  mount TinymceFm::Engine => "/tinymce_fm"

  resource :images

  resources :months do
    collection do
      post 'update_calendar'
    end
  end

  resources :areas do
    collection do
      post 'add_to_user'
      get 'list'
      delete 'remove_from_user'

    end
  end

  resources :requests

  resources :trainings do
    member do
      get 'add_participant'
      get 'del_participant'
    end
  end

  resources :grants do
    member do
      get 'add_participant'
      get 'del_participant'
    end
  end  

  resources :events do
    member do
      get 'add_participant'
      get 'del_participant'
    end
    collection do
      get 'activities'
      get 'not_approved'
      post 'update_index'
      post 'event_status'
      post 'event_delete'
    end
  end

  resources :resumes do
    get 'crop', :on => :member
  end
  put "update_avatar/:id" => "resumes#update_avatar"

  resources :compinfos do
    get 'crop', :on => :member
  end
  put "update_avatar_comp/:id" => "compinfos#update_avatar_comp"
  
  resources :pages

  get 'renew_password' => 'users#renew_password'
  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :sessions => "sessions",
    :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    get "sign_out", :to => "sessions#destroy"
    resources :resumes
    resources :compinfos
  end

  post "valid" => "users#valid"
  post "add_remove_event" => "users#add_remove_event"
  get '/change_emoution' => 'users#change_emoution'
  get 'reset_password/:token' => 'users#reset_password', :as => 'reset_password'
  put 'update_password/:id' => 'users#update_password', :as => 'update_password'
  get 'send_mails'=> 'users#send_mails'
  
  get "/profile" => "users#show"

  match "admin_page", :to => "users#admin_page", :as => :admin_page
  resources :users do #, :only => [:show, :index, :activities ]
    member do
      get "activities"
      get "userevents"      
      get "created_event"
    end
  end

  get "users/sphere", :as => 'sphere'

  root :to => 'events#index' 

  post "/post_find_location" => "connections#post_find_location"

  match '*a', :to => 'errors#routing'
end

app/models/resume.rb
#encoding: UTF-8
class Resume
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes  
  embedded_in :User

 # attr_accessible :experience_works_attributes, :photo, :name, :surname, :sex, :home, :education, :university, :faculty, :description, :delivery_email_enable, :delivery_email, :delivery_phone_enable, :delivery_phone, :birthday, :experation
 
  field :crop_x, :type => Integer
  field :crop_y, :type => Integer
  field :crop_w, :type => Integer
  field :crop_h, :type => Integer
  
  field :name, :type => String, :default => ""
  field :surname, :type => String, :default => ""
  field :gender, :type => String, :default => ""
  field :birthday, :type => Date
  field :home, :type => String, :default => ""
  field :education, :type => String, :default => ""
  field :university, :type => String, :default => ""
  field :faculty, :type => String, :default => ""
  field :experation, :type => Date
  field :description, :type => String, :default => ""
  field :delivery_email_enable, :type => Boolean
  field :delivery_email, :type => String , :default => ""
  field :delivery_phone_enable, :type => Boolean
  field :delivery_phone, :type => String, :default => ""
  field :sex, :type=>String, :default => ""

  mount_uploader :photo, ImageUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  has_many :experience_works, :dependent => :destroy
  accepts_nested_attributes_for :experience_works, :allow_destroy => true
  
  validate :photo,  :size => { :in => 0..5.megabytes }
  validates_format_of :photo, :with => %r{\.(jpg|jpeg)$}i, :message => "Неверный формат",  :if => "photo?"

  def picture_size_validation
    errors[:photo] << "5MB" if photo.size > 5.megabytes
  end

  def crop_avatar
    photo.recreate_versions! if crop_x.present?
  end


  def birthday_formatted
    self.birthday.strftime('%d.%m.%Y') if self.birthday?
  end
 
  def birthday_formatted=(value)
    self.birthday = Time.zone.parse(value)
  end  

  def experation_formatted
    self.experation.strftime('%d.%m.%Y') if self.experation?
  end
 
  def experation_formatted=(value)
    self.experation = Time.zone.parse(value)
  end  
end

app/controllers/resumes_controller.rb
# -*- encoding : utf-8 -*-
class ResumesController < ApplicationController
  
  require 'devise'
  # GET /resumes
  # GET /resumes.json
  def index

    @resumes = Resume.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resumes }
    end
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    @resume = current_user.try(:resume)#Resume.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/new
  # GET /resumes/new.json
  def new
    @resume = Resume.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/1/edit
  def edit
    @title = 'Личная информация'
    unless current_user.nil?
      @resume = current_user.resume #Resume.find(params[:id])
    else
      redirect_to root_path
    end
    @user = current_user
  end

  def crop
    @resume = current_user.resume    
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(params[:resume])
    current_user.resume = @resume
    respond_to do |format|
      if current_user.save
        if params[:resume][:photo].present?
          logger.debug "==========crop==============="
          render :crop
          logger.debug "==========crop==============="
        else
          format.html { redirect_to current_user, notice: 'Resume was successfully created.' }
          format.json { render json: @resume, status: :created, location: @resume }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update    
    @resume = current_user.resume #Resume.find(params[:id]) 

    if @resume.update_attributes(params[:resume]) 

      if params[:resume][:photo].present?
          #return render :json => {:url => @resume.photo.url(:large)}
          render :crop
      else
        redirect_to current_user, notice: 'Resume was successfully updated.'
        #format.html { redirect_to current_user, notice: 'Resume was successfully updated.' }
        #return render :json => {:url => @resume.photo.url(:large)}
      end
    else        
      redirect_to :controller => 'resumes', :action => "crop", :id => current_user.id
      #format.html { render action: "edit" }
       #format.json { render json: @resume.errors, status: :unprocessable_entity }
    end    
  end

  def update_avatar
    @resume = current_user.resume #if current_user #Resume.find(params[:id]) 
    #@resume = Resume.where(:id=>params[:resume]) if params[:resume]

    puts (@resume.inspect)

    if @resume.update_attributes(params[:resume])  

      if params[:resume][:photo].present?
        return render :json => {:url => @resume.photo.url(:large)}
        #render :crop
      else
        #redirect_to current_user, notice: 'Resume was successfully updated.'
        #format.html { redirect_to current_user, notice: 'Resume was successfully updated.' }
        return render :json => {:url => @resume.photo.url(:small)}
        #return render :json => {:url => compinfo.photo.url}
      end
    else      
      return render :json => {:error => 'Ошибка загрузки фотографии'}
      #redirect_to :controller => 'resumes', :action => "crop", :id => current_user.id
      #format.html { render action: "edit" }
      #format.json { render json: @resume.errors, status: :unprocessable_entity }
    end  
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy

    respond_to do |format|
      format.html { redirect_to resumes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_experience_work_fields.html.erb
<div class="nested-fields">
  <div class="input_field fr">
    <div class="sub_info_row">
      <span style='margin-left:-10px; width: 90px;'>КОМПАНИЯ</span> 
      <%= f.text_field :experience_company, :style => "width: 280px;", :class => 'company' %>
      <div class="clr"></div>
    </div>
    <div class="sub_info_row">
      <div class="fl" >
        <span style='width:25px; margin-left: -10px;'>C</span>        
        <%= f.text_field :experience_from_formatted, :style => 'width:170px;', :class => 'date-select', "data-title" => 'Календарь' %>
        <%#= f.date_select :experience_from, :start_year => 1950, :end_year => Date.today.year,
                      :order => [:day, :month, :year], :style => "width: 170px;" %>    
       </div>
      <div class="fr">
        <span style='width:20px;'>ПО</span>
        <%= f.text_field :experience_to_formatted, :style => 'width:170px;', :class => 'date-select', "data-title" => 'Календарь' %>        
        <%#= f.date_select :experience_to, :start_year => 1950, :end_year => Date.today.year,
                      :order => [:day, :month, :year], :style => "width: 170px;" %>      
       </div>
      <div class="clr"></div>
    </div>

    <div class="sub_info_row">
      <span style='width:90px; margin-left: -10px;'>ДОЛЖНОСТЬ</span>
      <%= f.text_field :experience_position, :style => "width:280px;"  %>    
      <div class="clr"></div>
    </div>
    <div class="delete_experience_work">
      УДАЛИТЬ <%= link_to_remove_association image_tag('delete.png'), f, :id => 'del' %>          
    </div>  
  </div>
  <div class="clr"></div>
</div>
<script>
// console.log($("#exper_fl select").attr("id"));
$(".fl select, .fr select").selectbox();

</script>

app/views/resumes/_form.html.erb
<div id="resume">
  <%= simple_form_for @resume do |f| %>
  <div class="block">
    <%= f.input :surname, :label => "ФАМИЛИЯ" %>
    <%= f.input :name, :label => "ИМЯ" %>
    <%= f.input :gender, :label => "ПОЛ", :collection => ["мужской", "женский"], :as => :radio_buttons  %>
    
    <div class="for_clear"></div>
    <!-- -->
        <%# f.input :photo, :label => "АВАТАР"  %>
    <!-- -->
    <%= f.input :birthday, :label => "ДЕНЬ РОЖДЕНИЯ", :as => :date, :start_year => Date.today.year - 50,
                              :end_year => Date.today.year - 10,
                              :order => [:day, :month, :year] %>
    <%= f.input :home, :label => "ГОРОД"  %>
    </div>
    <div class="line"></div>
    <div class="block">
    <%= f.input :education, :label => "ОБРАЗОВАНИЕ"  %>
    <%= f.input :university, :label => "ВУЗ", :wrapper_html =>{:class => "edu"} %>
    <%= f.input :faculty, :label => "ФАКУЛЬТЕТ", :wrapper_html =>{:class => "edu"}  %>
    <%= f.input :experation, :label => "ДАТА ОКОНЧАНИЯ", :as => :date, :start_year => Date.today.year - 50,
                :end_year => Date.today.year - 10,
                :order => [:day, :month, :year], :wrapper_html =>{:class => "edu"}  %>
    </div>
    <div class="line"></div>
    <div class="block">
    <label>ОПЫТ РАБОТЫ</label>
    <div id="experience">
    <%= f.input :experience_company, :label => "КОМПАНИЯ", :wrapper_html =>{:class => "edu"}  %>
    <%= f.input :experience_from, :label => "с", :wrapper_html =>{:class => "edu from"} %>
    <%= f.input :experience_to, :label => "по", :wrapper_html =>{:class => "edu to"} %>
    <%= f.input :experience_position, :label => "ДОЛЖНОСТЬ", :wrapper_html =>{:class => "edu position"}  %>
    </div>
    <input type="button" class="add_experience edu" value="ДОБАВИТЬ" />
    </div>
    <div class="line"></div>
    <div class="block">

    <%= f.input :description, :label => "ОПИСАНИЕ СЕБЯ", as: :text, :input_html => {:rows => "8", :cols => "65"}  %>
    </div>
    <div class="line"></div>
    <div class="block">
    <%= f.input :delivery_email_enable, :as => :boolean, :label => "ПОДПИСАТЬСЯ НА РАССЫЛКУ ПО ИНТЕРЕСУЮЩИМ МЕНЯ СФЕРАМ"  %>
    <div class="for_clear"></div>
    <%= f.input :delivery_email, :label => "E-MAIL", :wrapper_html =>{:class => "hd"}  %>
    </div>
    <div class="line"></div>
    <div class="block">
    <%= f.input :delivery_phone_enable, :as => :boolean, :label => "ПОДПИСАТЬ НА SMS-РАССЫЛКУ", :wrapper_html =>{:class => "sms-label"}  %>
    <div class="for_clear"></div>
    <%= f.input :delivery_phone, :label => "ВАШ МОБИЛЬНЫЙ ТЕЛЕФОН"  %>
    </div>
    <div class="line"></div>
    
    <%= link_to "СМЕНИТЬ ПАРОЛЬ", edit_registration_path(current_user), :class=> "edit"%>

    <%= f.button :submit, :value => "СОХРАНИТЬ" %>
  <% end %>
</div>  

app/views/resumes/crop.html.erb
<div id="content">
    <h1 class="ava-title">Выбор аватара</h1>
    <%= javascript_include_tag 'jquery.Jcrop.min' %>
    <%= javascript_include_tag 'jquery.color' %>
    <%= javascript_include_tag 'jquery.uniform.min' %>
    <%= javascript_include_tag 'resume' %>
    <% unless @resume.nil? %>
        <% if @resume.photo.url(:large) %>
            <div class='fl'>
                <%= image_tag @resume.photo.url(:large), id: "cropbox"%>
            </div>
            <div class='fl' style='width: 181px; margin-left:10px; margin-bottom: 30px'>
                 <span class="av-redact-title2">Миниатюры фотографии</span>
         Выберите область на основной фотографии, которая будет отображаться в миниатюрах на сайте

            </div>
            <div style="overflow: hidden; width: 100px; height: 100px; margin: 0 10px;" class='fl'>                    
                <%= image_tag @resume.photo.url, id: "preview" %>
            </div>
            <div style="overflow: hidden; width: 54px; height: 46px;" class='fl'>
                <%= image_tag @resume.photo.url, id: "preview2" %>
            </div>
            <div class='clr'></div>
        <% else %>
            <br>        
            <img id="" src = "/assets/nophoto.jpg">  
        <% end %>
        <%= simple_form_for @resume do |f| %>

            <div id="resume">
                <div class="ava-sep"></div>
                <p class="ava-text" style='color:green'>
                    *Файл должен бить не больше 5Mb, формат jpg или jpeg.
                </p>
                <p>
                <%= f.input :photo, :label => "АВАТАР", :class=>"ava-btn"  %>
                </p>                
            </div>



          <% %w[x y w h].each do |attribute| %>
            <%= f.hidden_field "crop_#{attribute}" %>
          <% end %>
          <div class="actions">
            <%= f.submit "Сохранить", :class=>"ava-btn" %>
          </div>
        <% end %>
    <% end %>
</div>

app/views/resumes/index.html.erb
<h1>Список всех резюме</h1>

<table>
  <tr>
    <th>Имя</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resumes.each do |resume| %>
  <tr>
    <td><%= resume.name %></td>
    <td><%= link_to 'Показать', resume %></td>
    <td><%= link_to 'Редактировать', edit_resume_path(resume) %></td>
    <td><%= link_to 'Удалить', resume, confirm: 'Вы уверены?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новое резюме', new_resume_path %>

app/views/resumes/new.html.erb
<div id="content">
  <div class="input_info">
    <div class="info_row">
      <span>ИМЯ</span>
      <div class="input_field">
        <input style="width:423px;" type="text" name="" id="">
      </div>
      <div class="clr"></div>
    </div>
    <div class="info_row">
      <span>ФАМИЛИЯ</span>
      <div class="input_field">
        <input style="width:423px;" type="text" name="" id="">
      </div>
      <div class="clr"></div>
    </div>
    <div class="info_row">
      <span>ПОЛ</span>
      <div class="clr"></div>
    </div>
    <div class="info_row">
      <span>ДАТА РОЖДЕНИЯ</span>
      <div class="input_field">
        <input style="width:15px;" type="text" name="" id="" maxlength="2">
        <input style="width:15px;" type="text" name="" id="" maxlength="2">
        <input style="width:40px;" type="text" name="" id="" maxlength="4">
      </div>
      <div class="clr"></div>
    </div>
    <div class="info_row">
      <span>МЕСТО ЖИТЕЛЬСТВА</span>
      <div class="input_field">
        <input style="width:423px;" type="text" name="" id="">
      </div>
      <div class="clr"></div>
    </div>
    <div class="sep"></div>

    <div class="info_row">
      <span>ОБРАЗОВАНИЕ</span>
      <div class="input_field">
        <input style="width:423px;" type="text" name="" id="">
        <div class="sub_info_row">
          ВУЗ <input style="width:280px;" type="text" name="" id="">
          <div class="clr"></div>
        </div>
        <div class="sub_info_row">
          ФАКУЛЬТЕТ <input style="width:280px;" type="text" name="" id="">
          <div class="clr"></div>
        </div>
        <div class="sub_info_row">
          ДАТА ОКОНЧАНИЯ <input style="width:280px;" type="text" name="" id="">
          <div class="clr"></div>
        </div>
      </div>
      <div class="clr"></div>
    </div>

    <div class="sep"></div>
    <div class="info_row">
      <span>ОПЫТ РАБОТЫ</span>
      <div class="input_field">
        <div class="sub_info_row">
          КОМПАНИЯ 1 <input style="width:280px;" type="text" name="" id="">
          <div class="clr"></div>
        </div>
        <div class="sub_info_row">
          <div class="fl">С <input style="width:180px;" type="text" name="" id="" class="fl"></div>
          <div class="fl">ПО <input class="fl" style="width:180px;" type="text" name="" id=""></div>
        </div>
        <div class="sub_info_row">
          ДОЛЖНОСТЬ <input style="width:280px;" type="text" name="" id="">
          <button>ДОБАВИТЬ</button>
          <div class="clr"></div>
        </div>

      </div>
      <div class="clr"></div>
    </div>

    <div class="sep"></div>

    <div class="info_row">
      <span>ОПИСАНИЕ СЕБЯ</span>
      <div class="input_field">
        <textarea></textarea>
      </div>
      <div class="clr"></div>
    </div>

    <div class="sep"></div>




    <div class="tv_sizeBig">
      <span>ПОДПИСАТЬСЯ НА РАССЫЛКУ ПО ИНТЕРЕСУЮЩИМ МЕНЯ СФЕРАМ</span>
      <input type="checkbox" name="" id="">
      <div class="clr"></div>
    </div>
    <div class="info_row">
      <div class="sub_info_row">
        <span>&nbsp;</span>E-MAIL <input style="width:375px;" type="text" name="" id="">
      </div>
    </div>
    <div class="clr"></div>
    <div class="sep"></div>
    <div class="tv_sizeBig">
      <span>ПОДПИСАТЬСЯ НА SMS-РАССЫЛКУ</span>
      <input type="checkbox" name="" id="">
      <div class="clr"></div>
    </div>
    <span>ВАШ МОБИЛЬНЫЙ ТЕЛЕФОН &nbsp;&nbsp;&nbsp;&nbsp;</span><input style="width:375px;" type="text" name="" id="">
    <div class="clr"></div>
    <div class="sep"></div>
    ИЗМЕНИТЬ ПАРОЛЬ
    <div class="clr"></div>
    <div class="info_row">
      <button>СОХРАНИТЬ</button>
    </div>
  </div>
</div>

app/views/resumes/show.html.erb
<div id="content">

  <div class="persinalInformation">
    <script type="text/javascript" src="js/jquery.jqtransform.js"></script>
    <script language="javascript">
        $(function(){
            $('.inputsOnPI, .fjqtrans, .catsItem, .pchecks').jqTransform();
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".pi").hover(function () {
                var thisIndex = $(this).index();
                if (thisIndex < 2) {
                    $(this).stop().animate({
                        "width":"100%"
                    },200);
                }  else if(thisIndex > 8){
                    $(this).prev().css({"borderWidth":"0"});
                    $(this).css({"borderWidth":"1px 0 1px 0"});
                    $(this).stop().animate({
                        "width":"100%"
                    },200);
                } else{
                    $(this).prev().css({"borderWidth":"0px"});
                    $(this).css({"borderWidth":"1px 0 1px 0"});
                    $(this).stop().animate({
                        "width":"100%"
                    },200);
                };
            }, function () {
                var thisIndex = $(this).index();
                if (thisIndex < 2) {
                    $(this).stop().animate({
                        "width":"610px"
                    },200);
                } else if(thisIndex > 8){
                    $(this).prev().css({"borderWidth":"0 0 1px 0"});
                    $(this).css({"borderWidth":"0px"});
                    $(this).stop().animate({
                        "width":"610px"
                    },200);

                } else {
                    $(this).prev().css({"borderWidth":"0px 0 1px 0"});
                    $(this).css({"borderWidth":"0px 0 1px 0"});
                    $(this).stop().animate({
                        "width":"610px"
                    },200);
                };
            });




            $(".persinalInformation .pi").each(function () {
                var a = $(this).outerHeight();
                var b = a/2 - 9;
                var b = b.toFixed();
                $(this).children("button").css({"top":b+"px"});

            });
        });
    </script>

    <div class="pi">
      <%= link_to edit_resume_path(current_user.id) if params[:id]==current_user.id %>
      <p class="greenUpper fll">Имя:</p>
      <p class="blackLower flr"><%= @resume.name %></p>
      <div class="clr"></div>
      <p class="greenUpper fll">Фамилия:</p>
      <p class="blackLower flr"><%= @resume.surname %></p>
      <div class="clr"></div>
      <p class="greenUpper fll">Пол:</p>
      <p class="blackLower flr"><%= @resume.gender %></p>
      <div class="clr"></div>
      <p class="greenUpper fll">Дата рождения:</p>
      <p class="blackLower flr"><%= @resume.birthday %></p>
      <div class="clr"></div>
      <p class="greenUpper fll">Место жительства:</p>
      <p class="blackLower flr"><%= @resume.home %></p>
      <div class="clr"></div>
    </div>
    <div class="pi">
      <%= link_to edit_resume_path(current_user.id) if params[:id]==current_user.id %>
      <p class="greenUpper fll">Образование:</p>
      <p class="blackLower flr"><%= @resume.education %></p>
      <div class="clr"></div>
      <p class="greenUpper fll">вуз:</p>
      <p class="blackLower flr"><%= @resume.university %></p>
      <div class="clr"></div>
      <p class="greenUpper fll">факультет:</p>
      <p class="blackLower flr"><%= @resume.faculty %></p>
      <div class="clr"></div>
      <p class="greenUpper fll">филологический:</p>
      <p class="blackLower flr"><%= @resume.experation %></p>
      <div class="clr"></div>
    </div>
    <div class="pi">
      <%= link_to edit_resume_path(current_user.id) if params[:id]==current_user.id %>
      <p class="blackLower flr mf"><span class="greenLower">с</span> <%= @resume.experience_from %> <span class="greenLower">по</span> <%= @resume.experience_to %></p>
      <div class="clr"></div>
      <p class="blackLower flr mf"><%= @resume.experience_company %></p>
      <div class="clr"></div>
      <p class="greenUpper fll wl2">Должность:</p>
      <p class="blackLower flr"><%= @resume.experience_position %></p>
      <div class="clr"></div>
    </div>
    <div class="pi">
      <%= link_to edit_resume_path(current_user.id) if params[:id]==current_user.id %>
      <p class="greenUpper fll">Описание себя:</p>
      <p class="blackLower flr"><%= @resume.description %></p>
      <div class="clr"></div>
    </div>
    <div class="pi">
      <%= link_to edit_resume_path(current_user.id) if params[:id]==current_user.id %>
      <p class="greenUpper fll wf">Подписатся на рассылку по интересующим меня сферам:</p>
      <div class="inputsOnPI"><input type="checkbox" name="" id="" checked="<%= @resume.delivery_email_enable ? 'checked' : '' %>"></div>
      <div class="clr"></div>
      <p class="greenUpper fll ml">e-mail</p>
      <p class="blackLower flr"><%= @resume.delivery_email %></p>
      <div class="clr"></div>
    </div>
    <div class="pi">
      <%= link_to edit_resume_path(current_user.id) if params[:id]==current_user.id %>
      <p class="greenUpper fll wf">Подписатся на sms-рассылку:</p>
      <div class="inputsOnPI"><input type="checkbox" name="" id="" checked="<%= @resume.delivery_phone_enable ? 'checked' : '' %>"></div>
      <div class="clr"></div>
      <p class="greenUpper fll wl1">ваш мобильный телефон</p>
      <p class="blackLower flr"><%= @resume.delivery_phone %></p>
      <div class="clr"></div>
    </div>
  </div>

  <div class="clr"></div>
</div>